// Generated by https://quicktype.io

export interface AreaResult {
    ok:   boolean;
    msg:  string;
    area: Area[];
}

export interface Area {
    id:              number;
    nombre:          string;
    sigla:           string;
    textoNumeracion: string;
    habilitado:      number;
    idDireccion:     number;
    Direccion:       Direccion;
}

export interface Direccion {
    id:     number;
    nombre: string;
}
