// Generated by https://quicktype.io

export interface ResultDestinoInterno {
    ok:       boolean;
    msg:      string;
    destinos: Destino[];
}

export interface Destino {
    id:              number;
    codigoTramite:   string;
    destinoArea:     number;
    accion:          string;
    atendido:        number;
    estadoRecepcion: number;
    Tramiteinterno:  Tramiteinterno;
}

export interface Tramiteinterno {
    codigo:          string;
    asunto:          string;
    referencia:      null | string;
    fecha:           string;
    ano:             string;
    idArea:          number;
    codigoDocumento: string;
    observacion:     string;
    hora:            string;
}
