// Generated by https://quicktype.io

export interface DocumentoInternoResult {
    ok: boolean;
    msg: string;
    documentoInter: DocumentoInterno[];
}

export interface DocumentoInterno {
    id: number;
    codigoDocumento: string;
    asunto: string;
    fecha: string;
    descripcion: string;
    referencia: null;
    estadoFirma: number;
    destino: string;
    codigo?: string;
    tipo?: string;
}
