// Generated by https://quicktype.io

export interface ResultEjemploDocument {
    ok:      boolean;
    msg:     string;
    ejemplo: EjemploDoc[];
}

export interface EjemploDoc {
    id:        number;
    titulo:    string;
    contenido: string;
    idUsuario: number;
}
