// Generated by https://quicktype.io

export interface LoginResult {
    ok:       boolean;
    userarea: Userarea;
    token:    string;
}

export interface Userarea {
    id:        number;
    idArea:    number;
    idUsuario: number;
    Usuario:   Usuario;
    areauser:  Areauser;
}

export interface Usuario {
    id:        number;
    nombre:    string;
    apellido:  string;
    tipoCargo: number;
    Cargo:     Cargo;
}

export interface Cargo {
    id:         number;
    nombre:     string;
    habilitado: number;
}

export interface Areauser {
    id:     number;
    nombre: string;
}
