// Generated by https://quicktype.io

export interface TipoDocResult {
    ok:            boolean;
    msg:           string;
    tipodocumento: Tipodocumento[];
}

export interface Tipodocumento {
    id:     number;
    nombre: string;
    sigla:  string;
}
