// Generated by https://quicktype.io

export interface ResultTramiteInterno {
    ok:           boolean;
    msg:          string;
    tramiteinter: Tramiteinter[];
}

export interface ResultTramiteInternoIndi {
    ok:           boolean;
    msg:          string;
    tramiteinter: Tramiteinter;
}
export interface Tramiteinter {
    codigo:          string;
    asunto:          string;
    referencia:      null | string;
    fecha:           string;
    ano:             string;
    idArea:          number;
    codigoDocumento: string;
    observacion:     string;
    hora:            string;
    Area?:            Area;
    Codigodocumento?: Codigodocumento;
}

export interface Area {
    id:     number;
    nombre: string;
}

export interface Codigodocumento {
    codigoUnico:   string;
    codigo:        string;
    tipoDocumento: number;
    idArea:        number;
    ano:           string;
}
